#pragma once

enum class EditorAction { 
    EXIT_CURRENT_TOOL, 
    ENTER_DRAW_TOOL, 
    ENTER_ERASE_TOOL,
    ENTER_TILE_SELECT_TOOL,
    PAN_CAMERA_UP,
    PAN_CAMERA_RIGHT,
    PAN_CAMERA_LEFT, 
    PAN_CAMERA_DOWN,
    COPY_SELECTION,
    PASTE_SELECTION,
    UNDO_ACTION,
    REDO_ACTION,
    ENTER_SELECTION_MOVE_TOOL,
    ENTER_PAINT_BUCKET_TOOL,
    EXECUTE_DRAW,
    EXECUTE_ERASE,
    EXECUTE_DRAG_MOVE,
    EXECUTE_PAINT_BUCKET
};